### ISSUE TITLE
Feature request: Recently visited channels

### ISSUE THREAD

**Issue by amnuts** [FreakyTurtle/elucidat-video#1]
Would be great to have a list of recently visited channels - maybe last three or five - appear on the channel input page, that way you could easily click on one to enter the room rather than having to type out the name.

Bonus points for having it configurable so you can change the number in the history or turn it off altogether.

**Comment by FreakyTurtle** [comment]
added in v.0.3.1 as auto suggestion, not added a feature to turn off auto suggestion as of yet, if you'd like that maybe open it as a new issue.  Curently it will remember your last 50 rooms
